### ISSUE TITLE
Unable to build firmware

### ISSUE THREAD

**Issue by spencerfolk** [josephyaconelli/crazyflie-firmware-pwm-control#2]
Hi there,

I'm trying to build your version of the firmware to run on my Crazyflie. I'm running into build errors and I'm wondering if you might have some insight. This is the error I get when I try to run `make all` like you would do if you were building the regular Crazyflie firmware. 

```
CLEAN_VERSION
  CC    crtp_commander_generic.o
In file included from src/modules/src/crtp_commander_generic.c:35:
/usr/include/newlib/math.h:133:12: error: expected identifier or '(' before 'double'
  133 | extern int isnan (double);
      |            ^~~~~
src/utils/interface/num.h:41:28: error: expected ')' before '?' token
   41 | #define isnan(n) ((n != n) ? 1 : 0)
      |                            ^
make[1]: *** [tools/make/targets.mk:27: crtp_commander_generic.o] Error 1
make: *** [Makefile:328: build] Error 2
```

Looks like it fails right off the bat. I think this has to do with the compiler version. If you recall, can you elaborate on how you built this firmware? What machine were you using? Which compiler? etc. 

Thanks!

**Comment by natolambert** [comment]
We were on Linux Ubuntu LTS 16 /18 (I can figure out what it is by asking some current students who have access to the machine on my old desk, if needed).

Not sure what else I remember, was almost 5 years ago on a research machine.

**Comment by spencerfolk** [comment]
I managed to flash this firmware on the Crazyflie... I think. I have yet to demonstrate it working with your ROS package. I switched to an older machine running Ubuntu 18.04.4 LTS and switched to `cflib v0.1.6` and `cfclient v2016.4.1` for loading it onto the CF. What was probably more important was having the right compiler, which was `g++ v7.5.0`.

**Comment by BerenChang** [comment]
> I managed to flash this firmware on the Crazyflie... I think. I have yet to demonstrate it working with your ROS package. I switched to an older machine running Ubuntu 18.04.4 LTS and switched to `cflib v0.1.6` and `cfclient v2016.4.1` for loading it onto the CF. What was probably more important was having the right compiler, which was `g++ v7.5.0`.

Sorry can you go a little bit into details about how to use g++v7.5 to compile the firmware? The makefile in this repository seems to use arm-none-eabi-gcc instead of g++v7.5 and I do not know how to change that to make the compile work.

**Comment by spencerfolk** [comment]
I'm not sure. If I recall, the issue I was having was the compiler was catching syntax issues that seemed to be a version issue when I Googled them. You might refer to this stackexchange for how to install a specific g++ compiler: 
https://askubuntu.com/questions/210871/how-to-install-a-specific-version-of-g

In retrospect, perhaps it wasn't the compiler issue and moreso me not following the right directions for compiling code, namely the instructions found here: https://www.bitcraze.io/documentation/repository/crazyflie-firmware/master/building-and-flashing/build/

**Comment by natolambert** [comment]
Y'all are speaking a language I can barely follow still, sorry I don't have better logs.
